# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
    files: ^src/
    exclude: ^src/libertem/web/client/
  - id: end-of-file-fixer
    files: ^src/
    exclude: ^src/libertem/web/client/
  - id: check-yaml
  - id: check-added-large-files
    exclude: ^src/libertem/web/client/assets
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    exclude: ^prototypes/
# pyroma failing in CI due to missing deps
# - repo: https://github.com/regebro/pyroma
#   rev: "4.2"
#   hooks:
#   - id: pyroma
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
    - id: pyupgrade
      args: ["--py310-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
  - id: mypy
    verbose: true
    entry: python ./scripts/run_mypy.py
